### ISSUE TITLE
Logging to remote tracking server becomes very slow when logging from larger number of parallel runs

### ISSUE THREAD

**Issue by fg91** [aimhubio/aim#2272]
## 🐛 Bug

In order to assess whether Aim can help us manage our large number of (parallelly running) experiments, we deployed a central tracking server instance and mocked logging from parallel runs to it. We observe that e.g. for ~100 parallel runs, a script that takes ~10s to run for a single instance all of a sudden takes in the order of ~10min.
We explored different resources and numbers of workers for the remote tracking server.

<img width="783" alt="Screenshot 2022-10-11 at 17 44 56" src="https://user-images.githubusercontent.com/36511035/195282552-681f36a5-780d-4227-a368-70ff956fe129.png">

### To reproduce

1. Deploy a remote tracking server e.g. on K8s
2. Run the following job:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: stress-test-configmap
  namespace: aim
data:
  stress_test.py: |
    import random
    import os

    import aim
    from aim import Run, Distribution

    N_EXPERIMENTS = 10
    N_TAGS = 10
    N_SUBTAGS = 10


    EXPERIMENT_ID = random.randint(0, N_EXPERIMENTS)
    TAG_ID = random.randint(0, N_TAGS)

    run = Run(
        repo=os.environ.get("AIM_TRACKING_URI"),
        experiment=f"experiment_{EXPERIMENT_ID}",
        system_tracking_interval=1,
    )

    #run.add_tag(f"experiment_{EXPERIMENT_ID}_tag_{TAG_ID}")
    #run.add_tag(f"experiemnt_{EXPERIMENT_ID}_tag_{TAG_ID}_subtag_{random.randint(0, N_SUBTAGS)}")

    # Log run parameters
    run['params'] = {
        'learning_rate': 0.001,
        'batch_size': 32,
    }

    its = os.environ.get("ITERATOINS", 100)

    for epoch in range(os.environ.get("EPOCHS", 3)):
        for it in range(its):
            print(f"Epoch: {epoch}, Iteration: {it}")
            progress = epoch * its + it + 1

            # aim - Track model loss function
            run.track(
                1./progress, name='loss',
                epoch=epoch,
                context={'subset':'train'}
            )

            if it % 10 == 0:
                d = Distribution(
                    distribution=[random.randrange(0, 10000) for _ in range(1000)],
                    bin_count=250
                )
                run.track(d, name='dist', step=progress)

---
apiVersion: batch/v1
kind: Job
metadata:
  name: aim-load-test
  namespace: aim
spec:
  ttlSecondsAfterFinished: 10
  parallelism: 100
  completions: 10000
  template:
    spec:
      volumes:
      - name: conf-volume
        configMap:
          name: stress-test-configmap
      containers:
      - name: client
        image: <image with aim>
        command: ["python"]
        args:
        - "stress_test.py"
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: "200m"
        env:
        - name: AIM_TRACKING_URI
          value: 'aim://aim-service:53800'
        volumeMounts:
          - name: conf-volume
            mountPath: /stress_test.py
            subPath: stress_test.py
      restartPolicy: Never
```

### Expected behavior

For teams, it would be great if the tracking server could handle this.

### Environment

- Aim Version 3.14.0 for both tracking server and client
- Python version 3.7
- pip version
- OS (e.g., Linux)
- Any other relevant information
