### ISSUE TITLE
Better visibility for hidden indicators 

### ISSUE THREAD

**Issue by YodaEmbedding** [aimhubio/aim#2321]
## 🚀 Feature

Better visibility for visible/hidden indicators.

### Motivation

Improves accessibility.

### Pitch

<img width="753" alt="aim_visibility" src="https://user-images.githubusercontent.com/721196/199939003-104be370-56d5-4199-bd30-666e0e0faa2c.png">

```css
  .Icon__container.icon-eye-show-outline {
    background: #ccffaa;
  }

  .Icon__container.icon-eye-outline-hide {
    opacity: 0.6;
  }
```

### Alternatives

Drinking more carrot juice.

### Additional context

N/A.
